---
- name: add debian repository
  apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present filename='jessie-backports' update_cache='yes'
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == "8"

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present default_release=jessie-backports"
  with_items: "{{ java_packages }}" 
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == "8"

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present default_release=jessie-backports"
  with_items: "{{ java_packages }}"
  when: ansible_distribution != 'Debian' and ansible_distribution_major_version != "8"   
